import { GetServerSidePropsContext, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import Link from "next/link";
import ActivityPage from "~/organisms/activityPage/ActivityPage";
import MainPage from "~/organisms/mainPage/MainPage";

export default function Home(
  props: InferGetServerSidePropsType<typeof getServerSideProps>,
) {
  return (
    <>
      <Head>
        <title>Duoasl</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ActivityPage activityId={props.activityId as string} />
    </>
  );
}

export const getServerSideProps = async (
  context: GetServerSidePropsContext,
) => {
  const { activityId } = context.query;
  return {
    props: {
      activityId,
    },
  };
};
